/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Video {
    id: VideoId;
    title: string;
    thumbnail: ExternalBlob;
    hashtags: Array<Hashtag>;
    description: string;
    likes: Array<UserId>;
    timestamp: Time;
    category: Category;
    uploader: UserId;
    comments: Array<Comment>;
    videoUrl: ExternalBlob;
}
export type MeetCategory = string;
export type Location = string;
export type Time = bigint;
export interface DirectMessage {
    id: MessageId;
    text: string;
    isRead: boolean;
    toUser: UserId;
    timestamp: Time;
    fromUser: UserId;
}
export interface MechanicsComment {
    id: CommentId;
    authorId: UserId;
    text: string;
    timestamp: Time;
    postId: bigint;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export type CommentId = bigint;
export interface Comment {
    id: CommentId;
    authorId: UserId;
    text: string;
    timestamp: Time;
    videoId: VideoId;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export type Category = string;
export type CarMeetId = string;
export interface CarMeet {
    id: CarMeetId;
    organizer: UserId;
    title: string;
    date: Time;
    createdAt: Time;
    description: string;
    attendees: Array<UserId>;
    category: MeetCategory;
    location: Location;
}
export interface MechanicsPost {
    id: bigint;
    title: string;
    createdAt: Time;
    description: string;
    author: UserId;
    category: string;
    comments: Array<MechanicsComment>;
}
export type UserId = Principal;
export type MessageId = bigint;
export type Hashtag = string;
export type VideoId = string;
export interface CarMeetDetails {
    id: CarMeetId;
    organizer?: UserProfile;
    title: string;
    date: Time;
    createdAt: Time;
    description: string;
    attendees: Array<UserProfile>;
    category: MeetCategory;
    location: Location;
}
export interface ConversationSummary {
    lastMessage: DirectMessage;
    otherUser: UserId;
    unreadCount: bigint;
}
export interface UserProfile {
    id: UserId;
    bio: string;
    username: string;
    avatarUrl: string;
    avatar: ExternalBlob;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    /**
     * / Add a comment to a video. Requires #user role.
     */
    addComment(videoId: VideoId, text: string): Promise<void>;
    /**
     * / Add a comment to a mechanics post. Requires #user role.
     */
    addMechanicsComment(postId: bigint, text: string): Promise<MechanicsComment>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    /**
     * / Create a new car meet/event. Requires #user role.
     */
    createCarMeet(title: string, location: Location, date: Time, description: string, category: MeetCategory): Promise<CarMeet>;
    /**
     * / Create a new mechanics post. Requires #user role.
     */
    createMechanicsPost(title: string, description: string, category: string): Promise<MechanicsPost>;
    /**
     * / Create a new user account. Open to all callers (guests register here).
     */
    createUser(username: string, bio: string, avatar: ExternalBlob, avatarUrl: string): Promise<UserProfile>;
    /**
     * / Delete a mechanics post. Only the author or an admin can delete.
     * / Requires #user role.
     */
    deleteMechanicsPost(postId: bigint): Promise<void>;
    /**
     * / Delete a message. Requires #user role.
     * / Only the sender of the message may delete it.
     */
    deleteMessage(otherUser: UserId, messageId: MessageId): Promise<void>;
    /**
     * / Delete a user account. Admin-only.
     */
    deleteUser(userId: UserId): Promise<void>;
    /**
     * / Delete a video and all associated comments and likes.
     * / Requires #user role. Only the uploader or an admin can delete.
     */
    deleteVideo(videoId: VideoId): Promise<void>;
    /**
     * / Follow another user. Requires #user role.
     */
    followUser(followee: UserId): Promise<void>;
    /**
     * / Get all car meets (sorted by date). Public.
     */
    getAllCarMeets(): Promise<Array<CarMeet>>;
    /**
     * / Get all mechanics posts. Public — no auth check needed.
     */
    getAllMechanicsPosts(): Promise<Array<MechanicsPost>>;
    /**
     * / Get all videos. Public — no auth check needed.
     */
    getAllVideos(): Promise<Array<Video>>;
    /**
     * / Get the caller's own profile. Requires #user role.
     */
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    /**
     * / Get a car meet by ID. Public.
     */
    getCarMeetById(meetId: CarMeetId): Promise<CarMeet | null>;
    /**
     * / Get detailed information on a car meet, including attendees' usernames and organizer. Public.
     */
    getCarMeetDetails(meetId: CarMeetId): Promise<CarMeetDetails | null>;
    /**
     * / Get car meets by category. Public.
     */
    getCarMeetsByCategory(category: MeetCategory): Promise<Array<CarMeet>>;
    /**
     * / Get car meets by organizer. Public.
     */
    getCarMeetsByOrganizer(organizer: UserId): Promise<Array<CarMeet>>;
    /**
     * / Get comments for a video. Public — no auth check needed.
     */
    getComments(videoId: VideoId): Promise<Array<Comment>>;
    /**
     * / Get all messages between the caller and another user, sorted by timestamp ascending.
     * / Requires #user role — only authenticated users can read their own conversations.
     */
    getConversation(otherUser: UserId): Promise<Array<DirectMessage>>;
    /**
     * / Get the inbox for the caller: most recent message per conversation partner,
     * / sorted by latest timestamp descending.
     * / Requires #user role — only authenticated users can read their own inbox.
     */
    getInbox(): Promise<Array<ConversationSummary>>;
    /**
     * / Get a mechanics post by ID. Public — no auth check needed.
     */
    getMechanicsPostById(postId: bigint): Promise<MechanicsPost | null>;
    /**
     * / Get the caller's own profile. Requires #user role.
     */
    getOwnProfile(): Promise<UserProfile>;
    /**
     * / Get any user's profile by principal. Public — no auth check needed.
     */
    getProfile(userId: UserId): Promise<UserProfile>;
    /**
     * / Get trending videos (top 10 by likes). Public — no auth check needed.
     */
    getTrendingVideos(): Promise<Array<Video>>;
    /**
     * / Get any user's profile by principal. Public — no auth check needed.
     */
    getUserProfile(userId: UserId): Promise<UserProfile | null>;
    /**
     * / Get a single video by ID. Public — no auth check needed.
     */
    getVideo(videoId: VideoId): Promise<Video>;
    /**
     * / Get videos filtered by category. Public — no auth check needed.
     */
    getVideosByCategory(category: Category): Promise<Array<Video>>;
    /**
     * / Get videos filtered by hashtag. Public — no auth check needed.
     */
    getVideosByHashtag(hashtag: Hashtag): Promise<Array<Video>>;
    /**
     * / Check if the caller is an admin. Public — no auth check needed (returns bool).
     */
    isAdmin(): Promise<boolean>;
    isCallerAdmin(): Promise<boolean>;
    /**
     * / Join a car meet. Requires #user role.
     */
    joinCarMeet(meetId: CarMeetId): Promise<CarMeet>;
    /**
     * / Leave a car meet. Requires #user role.
     */
    leaveCarMeet(meetId: CarMeetId): Promise<CarMeet>;
    /**
     * / Mark a specific message as read. Requires #user role.
     * / Only the recipient of the message may mark it as read.
     */
    markAsRead(otherUser: UserId, messageId: MessageId): Promise<void>;
    /**
     * / Save (create or update) the caller's profile. Requires #user role.
     */
    saveCallerUserProfile(username: string, bio: string, avatar: ExternalBlob, avatarUrl: string): Promise<void>;
    /**
     * / Send a direct message to another user. Requires #user role.
     */
    sendMessage(toUser: UserId, text: string): Promise<MessageId>;
    /**
     * / Toggle like on a video. Requires #user role.
     */
    toggleLike(videoId: VideoId): Promise<Video>;
    /**
     * / Unfollow another user. Requires #user role.
     */
    unfollowUser(followee: UserId): Promise<void>;
    updateAvatar(avatarUrl: string): Promise<UserProfile>;
    /**
     * / Update the caller's profile. Requires #user role.
     */
    updateProfile(username: string, bio: string, avatar: ExternalBlob, avatarUrl: string): Promise<UserProfile>;
    /**
     * / Upload a new video. Requires #user role.
     */
    uploadVideo(title: string, description: string, hashtags: Array<Hashtag>, category: Category, thumbnail: ExternalBlob, videoUrl: ExternalBlob): Promise<Video>;
}
import type { CarMeet as _CarMeet, CarMeetDetails as _CarMeetDetails, CarMeetId as _CarMeetId, Category as _Category, Comment as _Comment, ExternalBlob as _ExternalBlob, Hashtag as _Hashtag, Location as _Location, MechanicsPost as _MechanicsPost, MeetCategory as _MeetCategory, Time as _Time, UserId as _UserId, UserProfile as _UserProfile, UserRole as _UserRole, Video as _Video, VideoId as _VideoId, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addComment(arg0: VideoId, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addComment(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addComment(arg0, arg1);
            return result;
        }
    }
    async addMechanicsComment(arg0: bigint, arg1: string): Promise<MechanicsComment> {
        if (this.processError) {
            try {
                const result = await this.actor.addMechanicsComment(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addMechanicsComment(arg0, arg1);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createCarMeet(arg0: string, arg1: Location, arg2: Time, arg3: string, arg4: MeetCategory): Promise<CarMeet> {
        if (this.processError) {
            try {
                const result = await this.actor.createCarMeet(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCarMeet(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async createMechanicsPost(arg0: string, arg1: string, arg2: string): Promise<MechanicsPost> {
        if (this.processError) {
            try {
                const result = await this.actor.createMechanicsPost(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createMechanicsPost(arg0, arg1, arg2);
            return result;
        }
    }
    async createUser(arg0: string, arg1: string, arg2: ExternalBlob, arg3: string): Promise<UserProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.createUser(arg0, arg1, await to_candid_ExternalBlob_n10(this._uploadFile, this._downloadFile, arg2), arg3);
                return from_candid_UserProfile_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createUser(arg0, arg1, await to_candid_ExternalBlob_n10(this._uploadFile, this._downloadFile, arg2), arg3);
            return from_candid_UserProfile_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteMechanicsPost(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteMechanicsPost(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteMechanicsPost(arg0);
            return result;
        }
    }
    async deleteMessage(arg0: UserId, arg1: MessageId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteMessage(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteMessage(arg0, arg1);
            return result;
        }
    }
    async deleteUser(arg0: UserId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteUser(arg0);
            return result;
        }
    }
    async deleteVideo(arg0: VideoId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteVideo(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteVideo(arg0);
            return result;
        }
    }
    async followUser(arg0: UserId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.followUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.followUser(arg0);
            return result;
        }
    }
    async getAllCarMeets(): Promise<Array<CarMeet>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllCarMeets();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllCarMeets();
            return result;
        }
    }
    async getAllMechanicsPosts(): Promise<Array<MechanicsPost>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllMechanicsPosts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllMechanicsPosts();
            return result;
        }
    }
    async getAllVideos(): Promise<Array<Video>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllVideos();
                return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllVideos();
            return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCarMeetById(arg0: CarMeetId): Promise<CarMeet | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCarMeetById(arg0);
                return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCarMeetById(arg0);
            return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCarMeetDetails(arg0: CarMeetId): Promise<CarMeetDetails | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCarMeetDetails(arg0);
                return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCarMeetDetails(arg0);
            return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCarMeetsByCategory(arg0: MeetCategory): Promise<Array<CarMeet>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCarMeetsByCategory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCarMeetsByCategory(arg0);
            return result;
        }
    }
    async getCarMeetsByOrganizer(arg0: UserId): Promise<Array<CarMeet>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCarMeetsByOrganizer(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCarMeetsByOrganizer(arg0);
            return result;
        }
    }
    async getComments(arg0: VideoId): Promise<Array<Comment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getComments(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getComments(arg0);
            return result;
        }
    }
    async getConversation(arg0: UserId): Promise<Array<DirectMessage>> {
        if (this.processError) {
            try {
                const result = await this.actor.getConversation(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getConversation(arg0);
            return result;
        }
    }
    async getInbox(): Promise<Array<ConversationSummary>> {
        if (this.processError) {
            try {
                const result = await this.actor.getInbox();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInbox();
            return result;
        }
    }
    async getMechanicsPostById(arg0: bigint): Promise<MechanicsPost | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMechanicsPostById(arg0);
                return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMechanicsPostById(arg0);
            return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOwnProfile(): Promise<UserProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.getOwnProfile();
                return from_candid_UserProfile_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOwnProfile();
            return from_candid_UserProfile_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProfile(arg0: UserId): Promise<UserProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.getProfile(arg0);
                return from_candid_UserProfile_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProfile(arg0);
            return from_candid_UserProfile_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTrendingVideos(): Promise<Array<Video>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTrendingVideos();
                return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTrendingVideos();
            return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: UserId): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getVideo(arg0: VideoId): Promise<Video> {
        if (this.processError) {
            try {
                const result = await this.actor.getVideo(arg0);
                return from_candid_Video_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVideo(arg0);
            return from_candid_Video_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getVideosByCategory(arg0: Category): Promise<Array<Video>> {
        if (this.processError) {
            try {
                const result = await this.actor.getVideosByCategory(arg0);
                return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVideosByCategory(arg0);
            return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getVideosByHashtag(arg0: Hashtag): Promise<Array<Video>> {
        if (this.processError) {
            try {
                const result = await this.actor.getVideosByHashtag(arg0);
                return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVideosByHashtag(arg0);
            return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async isAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isAdmin();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async joinCarMeet(arg0: CarMeetId): Promise<CarMeet> {
        if (this.processError) {
            try {
                const result = await this.actor.joinCarMeet(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.joinCarMeet(arg0);
            return result;
        }
    }
    async leaveCarMeet(arg0: CarMeetId): Promise<CarMeet> {
        if (this.processError) {
            try {
                const result = await this.actor.leaveCarMeet(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.leaveCarMeet(arg0);
            return result;
        }
    }
    async markAsRead(arg0: UserId, arg1: MessageId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markAsRead(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markAsRead(arg0, arg1);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: string, arg1: string, arg2: ExternalBlob, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0, arg1, await to_candid_ExternalBlob_n10(this._uploadFile, this._downloadFile, arg2), arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0, arg1, await to_candid_ExternalBlob_n10(this._uploadFile, this._downloadFile, arg2), arg3);
            return result;
        }
    }
    async sendMessage(arg0: UserId, arg1: string): Promise<MessageId> {
        if (this.processError) {
            try {
                const result = await this.actor.sendMessage(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendMessage(arg0, arg1);
            return result;
        }
    }
    async toggleLike(arg0: VideoId): Promise<Video> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleLike(arg0);
                return from_candid_Video_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleLike(arg0);
            return from_candid_Video_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async unfollowUser(arg0: UserId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.unfollowUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unfollowUser(arg0);
            return result;
        }
    }
    async updateAvatar(arg0: string): Promise<UserProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAvatar(arg0);
                return from_candid_UserProfile_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAvatar(arg0);
            return from_candid_UserProfile_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateProfile(arg0: string, arg1: string, arg2: ExternalBlob, arg3: string): Promise<UserProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProfile(arg0, arg1, await to_candid_ExternalBlob_n10(this._uploadFile, this._downloadFile, arg2), arg3);
                return from_candid_UserProfile_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProfile(arg0, arg1, await to_candid_ExternalBlob_n10(this._uploadFile, this._downloadFile, arg2), arg3);
            return from_candid_UserProfile_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async uploadVideo(arg0: string, arg1: string, arg2: Array<Hashtag>, arg3: Category, arg4: ExternalBlob, arg5: ExternalBlob): Promise<Video> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadVideo(arg0, arg1, arg2, arg3, await to_candid_ExternalBlob_n10(this._uploadFile, this._downloadFile, arg4), await to_candid_ExternalBlob_n10(this._uploadFile, this._downloadFile, arg5));
                return from_candid_Video_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadVideo(arg0, arg1, arg2, arg3, await to_candid_ExternalBlob_n10(this._uploadFile, this._downloadFile, arg4), await to_candid_ExternalBlob_n10(this._uploadFile, this._downloadFile, arg5));
            return from_candid_Video_n15(this._uploadFile, this._downloadFile, result);
        }
    }
}
async function from_candid_CarMeetDetails_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CarMeetDetails): Promise<CarMeetDetails> {
    return await from_candid_record_n23(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
async function from_candid_UserProfile_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): Promise<UserProfile> {
    return await from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n19(_uploadFile, _downloadFile, value);
}
async function from_candid_Video_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Video): Promise<Video> {
    return await from_candid_record_n16(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
async function from_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): Promise<UserProfile | null> {
    return value.length === 0 ? null : await from_candid_UserProfile_n11(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_CarMeet]): CarMeet | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_CarMeetDetails]): Promise<CarMeetDetails | null> {
    return value.length === 0 ? null : await from_candid_CarMeetDetails_n22(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_MechanicsPost]): MechanicsPost | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _UserId;
    bio: string;
    username: string;
    avatarUrl: string;
    avatar: _ExternalBlob;
}): Promise<{
    id: UserId;
    bio: string;
    username: string;
    avatarUrl: string;
    avatar: ExternalBlob;
}> {
    return {
        id: value.id,
        bio: value.bio,
        username: value.username,
        avatarUrl: value.avatarUrl,
        avatar: await from_candid_ExternalBlob_n13(_uploadFile, _downloadFile, value.avatar)
    };
}
async function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _VideoId;
    title: string;
    thumbnail: _ExternalBlob;
    hashtags: Array<_Hashtag>;
    description: string;
    likes: Array<_UserId>;
    timestamp: _Time;
    category: _Category;
    uploader: _UserId;
    comments: Array<_Comment>;
    videoUrl: _ExternalBlob;
}): Promise<{
    id: VideoId;
    title: string;
    thumbnail: ExternalBlob;
    hashtags: Array<Hashtag>;
    description: string;
    likes: Array<UserId>;
    timestamp: Time;
    category: Category;
    uploader: UserId;
    comments: Array<Comment>;
    videoUrl: ExternalBlob;
}> {
    return {
        id: value.id,
        title: value.title,
        thumbnail: await from_candid_ExternalBlob_n13(_uploadFile, _downloadFile, value.thumbnail),
        hashtags: value.hashtags,
        description: value.description,
        likes: value.likes,
        timestamp: value.timestamp,
        category: value.category,
        uploader: value.uploader,
        comments: value.comments,
        videoUrl: await from_candid_ExternalBlob_n13(_uploadFile, _downloadFile, value.videoUrl)
    };
}
async function from_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _CarMeetId;
    organizer: [] | [_UserProfile];
    title: string;
    date: _Time;
    createdAt: _Time;
    description: string;
    attendees: Array<_UserProfile>;
    category: _MeetCategory;
    location: _Location;
}): Promise<{
    id: CarMeetId;
    organizer?: UserProfile;
    title: string;
    date: Time;
    createdAt: Time;
    description: string;
    attendees: Array<UserProfile>;
    category: MeetCategory;
    location: Location;
}> {
    return {
        id: value.id,
        organizer: record_opt_to_undefined(await from_candid_opt_n17(_uploadFile, _downloadFile, value.organizer)),
        title: value.title,
        date: value.date,
        createdAt: value.createdAt,
        description: value.description,
        attendees: await from_candid_vec_n24(_uploadFile, _downloadFile, value.attendees),
        category: value.category,
        location: value.location
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
async function from_candid_vec_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Video>): Promise<Array<Video>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Video_n15(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserProfile>): Promise<Array<UserProfile>> {
    return await Promise.all(value.map(async (x)=>await from_candid_UserProfile_n11(_uploadFile, _downloadFile, x)));
}
async function to_candid_ExternalBlob_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
