/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Video {
    id: VideoId;
    title: string;
    thumbnail: ExternalBlob;
    hashtags: Array<Hashtag>;
    description: string;
    likes: Array<UserId>;
    viewCount: bigint;
    timestamp: Time;
    category: Category;
    uploader: UserId;
    comments: Array<Comment>;
    videoUrl: ExternalBlob;
    reactions: Array<[UserId, ReactionType]>;
}
export type Location = string;
export interface UserStats {
    totalViews: bigint;
    joinedAt: bigint;
    totalLikes: bigint;
    totalFollowers: bigint;
    totalFollowing: bigint;
    totalVideos: bigint;
    totalBuildLogs: bigint;
    totalComments: bigint;
}
export type Time = bigint;
export interface BuildLog {
    id: bigint;
    stages: Array<BuildStage>;
    title: string;
    carModel: string;
    authorId: UserId;
    createdAt: bigint;
    description: string;
    updatedAt: bigint;
    carMake: string;
    carYear: string;
}
export interface MechanicsComment {
    id: CommentId;
    authorId: UserId;
    text: string;
    timestamp: Time;
    postId: bigint;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface CarMeet {
    id: CarMeetId;
    organizer: UserId;
    title: string;
    date: Time;
    createdAt: Time;
    description: string;
    attendees: Array<UserId>;
    category: MeetCategory;
    location: Location;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface RacingChallenge {
    id: bigint;
    status: string;
    createdAt: bigint;
    originalVideoId: bigint;
    challengedId: UserId;
    challengerId: UserId;
    videoId: bigint;
}
export type Hashtag = string;
export type VideoId = string;
export interface ConversationSummary {
    lastMessage: DirectMessage;
    otherUser: UserId;
    unreadCount: bigint;
}
export type Category = string;
export interface DirectMessage {
    id: MessageId;
    text: string;
    isRead: boolean;
    toUser: UserId;
    timestamp: Time;
    fromUser: UserId;
}
export type CarMeetId = string;
export type MeetCategory = string;
export type CommentId = bigint;
export interface Comment {
    id: CommentId;
    authorId: UserId;
    text: string;
    timestamp: Time;
    videoId: VideoId;
}
export interface Listing {
    id: bigint;
    model: string;
    title: string;
    make: string;
    createdAt: bigint;
    year: string;
    description: string;
    isActive: boolean;
    imageUrl: string;
    category: string;
    sellerId: UserId;
    price: string;
    condition: string;
}
export interface BuildStage {
    id: bigint;
    title: string;
    createdAt: bigint;
    description: string;
    imageUrl: string;
}
export interface MechanicsPost {
    id: bigint;
    title: string;
    createdAt: Time;
    description: string;
    author: UserId;
    category: string;
    comments: Array<MechanicsComment>;
}
export type UserId = Principal;
export type Result = {
    __kind__: "ok";
    ok: string;
} | {
    __kind__: "err";
    err: string;
};
export type MessageId = bigint;
export interface Notification {
    id: bigint;
    notificationType: string;
    createdAt: bigint;
    referenceId: string;
    isRead: boolean;
    message: string;
    recipientId: UserId;
    senderId: UserId;
}
export interface CarMeetDetails {
    id: CarMeetId;
    organizer?: UserProfile;
    title: string;
    date: Time;
    createdAt: Time;
    description: string;
    attendees: Array<UserProfile>;
    category: MeetCategory;
    location: Location;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface UserProfile {
    id: UserId;
    bio: string;
    verified: boolean;
    username: string;
    badges: Array<Badge>;
    joinedAt: bigint;
    avatarUrl: string;
    savedVideos: Array<bigint>;
    avatar: ExternalBlob;
}
export enum Badge {
    buildMaster = "buildMaster",
    verified = "verified",
    racingLegend = "racingLegend",
    dragRacer = "dragRacer",
    communityHelper = "communityHelper",
    driftKing = "driftKing",
    mechanicPro = "mechanicPro"
}
export enum ReactionType {
    fire = "fire",
    hype = "hype",
    like = "like",
    wild = "wild",
    respect = "respect"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addBuildStage(buildLogId: bigint, stageTitle: string, stageDescription: string, imageUrl: string): Promise<Result>;
    addComment(videoId: VideoId, text: string): Promise<void>;
    addMechanicsComment(postId: bigint, text: string): Promise<MechanicsComment>;
    addReaction(videoId: VideoId, reaction: ReactionType): Promise<Result>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    awardBadge(targetPrincipal: Principal, badge: Badge): Promise<Result>;
    closeChallenge(id: bigint): Promise<Result>;
    createBuildLog(title: string, carMake: string, carModel: string, carYear: string, description: string): Promise<Result>;
    createCarMeet(title: string, location: Location, date: Time, description: string, category: MeetCategory): Promise<CarMeet>;
    createListing(title: string, description: string, make: string, model: string, year: string, price: string, condition: string, imageUrl: string, category: string): Promise<Result>;
    createMechanicsPost(title: string, description: string, category: string): Promise<MechanicsPost>;
    createUser(username: string, bio: string, avatar: ExternalBlob, avatarUrl: string): Promise<UserProfile>;
    deactivateListing(id: bigint): Promise<Result>;
    deleteBuildLog(id: bigint): Promise<Result>;
    deleteMechanicsPost(postId: bigint): Promise<void>;
    deleteMessage(otherUser: UserId, messageId: MessageId): Promise<void>;
    deleteUser(userId: UserId): Promise<void>;
    deleteVideo(videoId: VideoId): Promise<void>;
    followUser(followee: UserId): Promise<void>;
    getAllActiveListings(): Promise<Array<Listing>>;
    getAllBuildLogs(): Promise<Array<BuildLog>>;
    getAllCarMeets(): Promise<Array<CarMeet>>;
    getAllMechanicsPosts(): Promise<Array<MechanicsPost>>;
    getAllUsers(): Promise<Array<UserProfile>>;
    getAllVideos(): Promise<Array<Video>>;
    getBuildLogById(id: bigint): Promise<BuildLog | null>;
    getBuildLogsByUser(principal: Principal): Promise<Array<BuildLog>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCarMeetById(meetId: CarMeetId): Promise<CarMeet | null>;
    getCarMeetDetails(meetId: CarMeetId): Promise<CarMeetDetails | null>;
    getCarMeetsByCategory(category: MeetCategory): Promise<Array<CarMeet>>;
    getCarMeetsByOrganizer(organizer: UserId): Promise<Array<CarMeet>>;
    getChallengesForUser(principal: Principal): Promise<Array<RacingChallenge>>;
    getChallengesForVideo(videoId: bigint): Promise<Array<RacingChallenge>>;
    getComments(videoId: VideoId): Promise<Array<Comment>>;
    getConversation(otherUser: UserId): Promise<Array<DirectMessage>>;
    getInbox(): Promise<Array<ConversationSummary>>;
    getListingById(id: bigint): Promise<Listing | null>;
    getListingsBySeller(principal: Principal): Promise<Array<Listing>>;
    getMechanicsPostById(postId: bigint): Promise<MechanicsPost | null>;
    getNotifications(): Promise<Array<Notification>>;
    getOwnProfile(): Promise<UserProfile>;
    getProfile(userId: UserId): Promise<UserProfile>;
    getReactionCounts(videoId: VideoId): Promise<Array<[ReactionType, bigint]>>;
    getSavedVideos(): Promise<Array<Video>>;
    getTrendingVideos(): Promise<Array<Video>>;
    getUnreadNotificationCount(): Promise<bigint>;
    getUserBadges(principal: Principal): Promise<Array<Badge>>;
    getUserProfile(userId: UserId): Promise<UserProfile | null>;
    getUserStats(principal: Principal): Promise<UserStats>;
    getVideo(videoId: VideoId): Promise<Video>;
    getVideoById(videoId: VideoId): Promise<Video | null>;
    getVideosByCategory(category: Category): Promise<Array<Video>>;
    getVideosByHashtag(hashtag: Hashtag): Promise<Array<Video>>;
    incrementViewCount(videoId: VideoId): Promise<void>;
    isAdmin(): Promise<boolean>;
    isCallerAdmin(): Promise<boolean>;
    joinCarMeet(meetId: CarMeetId): Promise<CarMeet>;
    leaveCarMeet(meetId: CarMeetId): Promise<CarMeet>;
    markAllNotificationsRead(): Promise<Result>;
    markAsRead(otherUser: UserId, messageId: MessageId): Promise<void>;
    markNotificationRead(notifId: bigint): Promise<Result>;
    postChallenge(originalVideoId: bigint, responseVideoId: bigint, challengedPrincipal: Principal): Promise<Result>;
    removeReaction(videoId: VideoId): Promise<Result>;
    saveCallerUserProfile(username: string, bio: string, avatar: ExternalBlob, avatarUrl: string): Promise<void>;
    saveVideo(videoId: bigint): Promise<Result>;
    sendMessage(toUser: UserId, text: string): Promise<MessageId>;
    setVerified(targetPrincipal: Principal, verified: boolean): Promise<Result>;
    toggleLike(videoId: VideoId): Promise<Video>;
    unfollowUser(followee: UserId): Promise<void>;
    unsaveVideo(videoId: bigint): Promise<Result>;
    updateAvatar(avatarUrl: string): Promise<UserProfile>;
    updateProfile(username: string, bio: string, avatar: ExternalBlob, avatarUrl: string): Promise<UserProfile>;
    uploadVideo(title: string, description: string, hashtags: Array<Hashtag>, category: Category, thumbnail: ExternalBlob, videoUrl: ExternalBlob): Promise<Video>;
}
import type { Badge as _Badge, BuildLog as _BuildLog, CarMeet as _CarMeet, CarMeetDetails as _CarMeetDetails, CarMeetId as _CarMeetId, Category as _Category, Comment as _Comment, ExternalBlob as _ExternalBlob, Hashtag as _Hashtag, Listing as _Listing, Location as _Location, MechanicsPost as _MechanicsPost, MeetCategory as _MeetCategory, ReactionType as _ReactionType, Result as _Result, Time as _Time, UserId as _UserId, UserProfile as _UserProfile, UserRole as _UserRole, Video as _Video, VideoId as _VideoId, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addBuildStage(arg0: bigint, arg1: string, arg2: string, arg3: string): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.addBuildStage(arg0, arg1, arg2, arg3);
                return from_candid_Result_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addBuildStage(arg0, arg1, arg2, arg3);
            return from_candid_Result_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async addComment(arg0: VideoId, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addComment(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addComment(arg0, arg1);
            return result;
        }
    }
    async addMechanicsComment(arg0: bigint, arg1: string): Promise<MechanicsComment> {
        if (this.processError) {
            try {
                const result = await this.actor.addMechanicsComment(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addMechanicsComment(arg0, arg1);
            return result;
        }
    }
    async addReaction(arg0: VideoId, arg1: ReactionType): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.addReaction(arg0, to_candid_ReactionType_n10(this._uploadFile, this._downloadFile, arg1));
                return from_candid_Result_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addReaction(arg0, to_candid_ReactionType_n10(this._uploadFile, this._downloadFile, arg1));
            return from_candid_Result_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n12(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n12(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async awardBadge(arg0: Principal, arg1: Badge): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.awardBadge(arg0, to_candid_Badge_n14(this._uploadFile, this._downloadFile, arg1));
                return from_candid_Result_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.awardBadge(arg0, to_candid_Badge_n14(this._uploadFile, this._downloadFile, arg1));
            return from_candid_Result_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async closeChallenge(arg0: bigint): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.closeChallenge(arg0);
                return from_candid_Result_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.closeChallenge(arg0);
            return from_candid_Result_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async createBuildLog(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.createBuildLog(arg0, arg1, arg2, arg3, arg4);
                return from_candid_Result_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createBuildLog(arg0, arg1, arg2, arg3, arg4);
            return from_candid_Result_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async createCarMeet(arg0: string, arg1: Location, arg2: Time, arg3: string, arg4: MeetCategory): Promise<CarMeet> {
        if (this.processError) {
            try {
                const result = await this.actor.createCarMeet(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCarMeet(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async createListing(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string, arg6: string, arg7: string, arg8: string): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.createListing(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
                return from_candid_Result_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createListing(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
            return from_candid_Result_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async createMechanicsPost(arg0: string, arg1: string, arg2: string): Promise<MechanicsPost> {
        if (this.processError) {
            try {
                const result = await this.actor.createMechanicsPost(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createMechanicsPost(arg0, arg1, arg2);
            return result;
        }
    }
    async createUser(arg0: string, arg1: string, arg2: ExternalBlob, arg3: string): Promise<UserProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.createUser(arg0, arg1, await to_candid_ExternalBlob_n16(this._uploadFile, this._downloadFile, arg2), arg3);
                return from_candid_UserProfile_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createUser(arg0, arg1, await to_candid_ExternalBlob_n16(this._uploadFile, this._downloadFile, arg2), arg3);
            return from_candid_UserProfile_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async deactivateListing(arg0: bigint): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.deactivateListing(arg0);
                return from_candid_Result_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deactivateListing(arg0);
            return from_candid_Result_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteBuildLog(arg0: bigint): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteBuildLog(arg0);
                return from_candid_Result_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteBuildLog(arg0);
            return from_candid_Result_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteMechanicsPost(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteMechanicsPost(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteMechanicsPost(arg0);
            return result;
        }
    }
    async deleteMessage(arg0: UserId, arg1: MessageId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteMessage(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteMessage(arg0, arg1);
            return result;
        }
    }
    async deleteUser(arg0: UserId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteUser(arg0);
            return result;
        }
    }
    async deleteVideo(arg0: VideoId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteVideo(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteVideo(arg0);
            return result;
        }
    }
    async followUser(arg0: UserId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.followUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.followUser(arg0);
            return result;
        }
    }
    async getAllActiveListings(): Promise<Array<Listing>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllActiveListings();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllActiveListings();
            return result;
        }
    }
    async getAllBuildLogs(): Promise<Array<BuildLog>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllBuildLogs();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllBuildLogs();
            return result;
        }
    }
    async getAllCarMeets(): Promise<Array<CarMeet>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllCarMeets();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllCarMeets();
            return result;
        }
    }
    async getAllMechanicsPosts(): Promise<Array<MechanicsPost>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllMechanicsPosts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllMechanicsPosts();
            return result;
        }
    }
    async getAllUsers(): Promise<Array<UserProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllUsers();
                return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllUsers();
            return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllVideos(): Promise<Array<Video>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllVideos();
                return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllVideos();
            return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBuildLogById(arg0: bigint): Promise<BuildLog | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getBuildLogById(arg0);
                return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBuildLogById(arg0);
            return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBuildLogsByUser(arg0: Principal): Promise<Array<BuildLog>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBuildLogsByUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBuildLogsByUser(arg0);
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCarMeetById(arg0: CarMeetId): Promise<CarMeet | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCarMeetById(arg0);
                return from_candid_opt_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCarMeetById(arg0);
            return from_candid_opt_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCarMeetDetails(arg0: CarMeetId): Promise<CarMeetDetails | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCarMeetDetails(arg0);
                return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCarMeetDetails(arg0);
            return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCarMeetsByCategory(arg0: MeetCategory): Promise<Array<CarMeet>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCarMeetsByCategory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCarMeetsByCategory(arg0);
            return result;
        }
    }
    async getCarMeetsByOrganizer(arg0: UserId): Promise<Array<CarMeet>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCarMeetsByOrganizer(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCarMeetsByOrganizer(arg0);
            return result;
        }
    }
    async getChallengesForUser(arg0: Principal): Promise<Array<RacingChallenge>> {
        if (this.processError) {
            try {
                const result = await this.actor.getChallengesForUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getChallengesForUser(arg0);
            return result;
        }
    }
    async getChallengesForVideo(arg0: bigint): Promise<Array<RacingChallenge>> {
        if (this.processError) {
            try {
                const result = await this.actor.getChallengesForVideo(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getChallengesForVideo(arg0);
            return result;
        }
    }
    async getComments(arg0: VideoId): Promise<Array<Comment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getComments(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getComments(arg0);
            return result;
        }
    }
    async getConversation(arg0: UserId): Promise<Array<DirectMessage>> {
        if (this.processError) {
            try {
                const result = await this.actor.getConversation(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getConversation(arg0);
            return result;
        }
    }
    async getInbox(): Promise<Array<ConversationSummary>> {
        if (this.processError) {
            try {
                const result = await this.actor.getInbox();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInbox();
            return result;
        }
    }
    async getListingById(arg0: bigint): Promise<Listing | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getListingById(arg0);
                return from_candid_opt_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getListingById(arg0);
            return from_candid_opt_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async getListingsBySeller(arg0: Principal): Promise<Array<Listing>> {
        if (this.processError) {
            try {
                const result = await this.actor.getListingsBySeller(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getListingsBySeller(arg0);
            return result;
        }
    }
    async getMechanicsPostById(arg0: bigint): Promise<MechanicsPost | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMechanicsPostById(arg0);
                return from_candid_opt_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMechanicsPostById(arg0);
            return from_candid_opt_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async getNotifications(): Promise<Array<Notification>> {
        if (this.processError) {
            try {
                const result = await this.actor.getNotifications();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNotifications();
            return result;
        }
    }
    async getOwnProfile(): Promise<UserProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.getOwnProfile();
                return from_candid_UserProfile_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOwnProfile();
            return from_candid_UserProfile_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProfile(arg0: UserId): Promise<UserProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.getProfile(arg0);
                return from_candid_UserProfile_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProfile(arg0);
            return from_candid_UserProfile_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getReactionCounts(arg0: VideoId): Promise<Array<[ReactionType, bigint]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getReactionCounts(arg0);
                return from_candid_vec_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReactionCounts(arg0);
            return from_candid_vec_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSavedVideos(): Promise<Array<Video>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSavedVideos();
                return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSavedVideos();
            return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTrendingVideos(): Promise<Array<Video>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTrendingVideos();
                return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTrendingVideos();
            return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUnreadNotificationCount(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getUnreadNotificationCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUnreadNotificationCount();
            return result;
        }
    }
    async getUserBadges(arg0: Principal): Promise<Array<Badge>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserBadges(arg0);
                return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserBadges(arg0);
            return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: UserId): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserStats(arg0: Principal): Promise<UserStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserStats(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserStats(arg0);
            return result;
        }
    }
    async getVideo(arg0: VideoId): Promise<Video> {
        if (this.processError) {
            try {
                const result = await this.actor.getVideo(arg0);
                return from_candid_Video_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVideo(arg0);
            return from_candid_Video_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getVideoById(arg0: VideoId): Promise<Video | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getVideoById(arg0);
                return from_candid_opt_n43(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVideoById(arg0);
            return from_candid_opt_n43(this._uploadFile, this._downloadFile, result);
        }
    }
    async getVideosByCategory(arg0: Category): Promise<Array<Video>> {
        if (this.processError) {
            try {
                const result = await this.actor.getVideosByCategory(arg0);
                return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVideosByCategory(arg0);
            return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getVideosByHashtag(arg0: Hashtag): Promise<Array<Video>> {
        if (this.processError) {
            try {
                const result = await this.actor.getVideosByHashtag(arg0);
                return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVideosByHashtag(arg0);
            return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async incrementViewCount(arg0: VideoId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.incrementViewCount(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.incrementViewCount(arg0);
            return result;
        }
    }
    async isAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isAdmin();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async joinCarMeet(arg0: CarMeetId): Promise<CarMeet> {
        if (this.processError) {
            try {
                const result = await this.actor.joinCarMeet(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.joinCarMeet(arg0);
            return result;
        }
    }
    async leaveCarMeet(arg0: CarMeetId): Promise<CarMeet> {
        if (this.processError) {
            try {
                const result = await this.actor.leaveCarMeet(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.leaveCarMeet(arg0);
            return result;
        }
    }
    async markAllNotificationsRead(): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.markAllNotificationsRead();
                return from_candid_Result_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markAllNotificationsRead();
            return from_candid_Result_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async markAsRead(arg0: UserId, arg1: MessageId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markAsRead(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markAsRead(arg0, arg1);
            return result;
        }
    }
    async markNotificationRead(arg0: bigint): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.markNotificationRead(arg0);
                return from_candid_Result_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markNotificationRead(arg0);
            return from_candid_Result_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async postChallenge(arg0: bigint, arg1: bigint, arg2: Principal): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.postChallenge(arg0, arg1, arg2);
                return from_candid_Result_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.postChallenge(arg0, arg1, arg2);
            return from_candid_Result_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async removeReaction(arg0: VideoId): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.removeReaction(arg0);
                return from_candid_Result_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeReaction(arg0);
            return from_candid_Result_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async saveCallerUserProfile(arg0: string, arg1: string, arg2: ExternalBlob, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0, arg1, await to_candid_ExternalBlob_n16(this._uploadFile, this._downloadFile, arg2), arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0, arg1, await to_candid_ExternalBlob_n16(this._uploadFile, this._downloadFile, arg2), arg3);
            return result;
        }
    }
    async saveVideo(arg0: bigint): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.saveVideo(arg0);
                return from_candid_Result_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveVideo(arg0);
            return from_candid_Result_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async sendMessage(arg0: UserId, arg1: string): Promise<MessageId> {
        if (this.processError) {
            try {
                const result = await this.actor.sendMessage(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendMessage(arg0, arg1);
            return result;
        }
    }
    async setVerified(arg0: Principal, arg1: boolean): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.setVerified(arg0, arg1);
                return from_candid_Result_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setVerified(arg0, arg1);
            return from_candid_Result_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async toggleLike(arg0: VideoId): Promise<Video> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleLike(arg0);
                return from_candid_Video_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleLike(arg0);
            return from_candid_Video_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async unfollowUser(arg0: UserId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.unfollowUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unfollowUser(arg0);
            return result;
        }
    }
    async unsaveVideo(arg0: bigint): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.unsaveVideo(arg0);
                return from_candid_Result_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unsaveVideo(arg0);
            return from_candid_Result_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateAvatar(arg0: string): Promise<UserProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAvatar(arg0);
                return from_candid_UserProfile_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAvatar(arg0);
            return from_candid_UserProfile_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateProfile(arg0: string, arg1: string, arg2: ExternalBlob, arg3: string): Promise<UserProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProfile(arg0, arg1, await to_candid_ExternalBlob_n16(this._uploadFile, this._downloadFile, arg2), arg3);
                return from_candid_UserProfile_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProfile(arg0, arg1, await to_candid_ExternalBlob_n16(this._uploadFile, this._downloadFile, arg2), arg3);
            return from_candid_UserProfile_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async uploadVideo(arg0: string, arg1: string, arg2: Array<Hashtag>, arg3: Category, arg4: ExternalBlob, arg5: ExternalBlob): Promise<Video> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadVideo(arg0, arg1, arg2, arg3, await to_candid_ExternalBlob_n16(this._uploadFile, this._downloadFile, arg4), await to_candid_ExternalBlob_n16(this._uploadFile, this._downloadFile, arg5));
                return from_candid_Video_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadVideo(arg0, arg1, arg2, arg3, await to_candid_ExternalBlob_n16(this._uploadFile, this._downloadFile, arg4), await to_candid_ExternalBlob_n16(this._uploadFile, this._downloadFile, arg5));
            return from_candid_Video_n25(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_Badge_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Badge): Badge {
    return from_candid_variant_n21(_uploadFile, _downloadFile, value);
}
async function from_candid_CarMeetDetails_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CarMeetDetails): Promise<CarMeetDetails> {
    return await from_candid_record_n38(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_ReactionType_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ReactionType): ReactionType {
    return from_candid_variant_n30(_uploadFile, _downloadFile, value);
}
function from_candid_Result_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result): Result {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
async function from_candid_UserProfile_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): Promise<UserProfile> {
    return await from_candid_record_n18(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n34(_uploadFile, _downloadFile, value);
}
async function from_candid_Video_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Video): Promise<Video> {
    return await from_candid_record_n26(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_BuildLog]): BuildLog | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): Promise<UserProfile | null> {
    return value.length === 0 ? null : await from_candid_UserProfile_n17(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_CarMeet]): CarMeet | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_CarMeetDetails]): Promise<CarMeetDetails | null> {
    return value.length === 0 ? null : await from_candid_CarMeetDetails_n37(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Listing]): Listing | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_MechanicsPost]): MechanicsPost | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Video]): Promise<Video | null> {
    return value.length === 0 ? null : await from_candid_Video_n25(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _UserId;
    bio: string;
    verified: boolean;
    username: string;
    badges: Array<_Badge>;
    joinedAt: bigint;
    avatarUrl: string;
    savedVideos: Array<bigint>;
    avatar: _ExternalBlob;
}): Promise<{
    id: UserId;
    bio: string;
    verified: boolean;
    username: string;
    badges: Array<Badge>;
    joinedAt: bigint;
    avatarUrl: string;
    savedVideos: Array<bigint>;
    avatar: ExternalBlob;
}> {
    return {
        id: value.id,
        bio: value.bio,
        verified: value.verified,
        username: value.username,
        badges: from_candid_vec_n19(_uploadFile, _downloadFile, value.badges),
        joinedAt: value.joinedAt,
        avatarUrl: value.avatarUrl,
        savedVideos: value.savedVideos,
        avatar: await from_candid_ExternalBlob_n22(_uploadFile, _downloadFile, value.avatar)
    };
}
async function from_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _VideoId;
    title: string;
    thumbnail: _ExternalBlob;
    hashtags: Array<_Hashtag>;
    description: string;
    likes: Array<_UserId>;
    viewCount: bigint;
    timestamp: _Time;
    category: _Category;
    uploader: _UserId;
    comments: Array<_Comment>;
    videoUrl: _ExternalBlob;
    reactions: Array<[_UserId, _ReactionType]>;
}): Promise<{
    id: VideoId;
    title: string;
    thumbnail: ExternalBlob;
    hashtags: Array<Hashtag>;
    description: string;
    likes: Array<UserId>;
    viewCount: bigint;
    timestamp: Time;
    category: Category;
    uploader: UserId;
    comments: Array<Comment>;
    videoUrl: ExternalBlob;
    reactions: Array<[UserId, ReactionType]>;
}> {
    return {
        id: value.id,
        title: value.title,
        thumbnail: await from_candid_ExternalBlob_n22(_uploadFile, _downloadFile, value.thumbnail),
        hashtags: value.hashtags,
        description: value.description,
        likes: value.likes,
        viewCount: value.viewCount,
        timestamp: value.timestamp,
        category: value.category,
        uploader: value.uploader,
        comments: value.comments,
        videoUrl: await from_candid_ExternalBlob_n22(_uploadFile, _downloadFile, value.videoUrl),
        reactions: from_candid_vec_n27(_uploadFile, _downloadFile, value.reactions)
    };
}
async function from_candid_record_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _CarMeetId;
    organizer: [] | [_UserProfile];
    title: string;
    date: _Time;
    createdAt: _Time;
    description: string;
    attendees: Array<_UserProfile>;
    category: _MeetCategory;
    location: _Location;
}): Promise<{
    id: CarMeetId;
    organizer?: UserProfile;
    title: string;
    date: Time;
    createdAt: Time;
    description: string;
    attendees: Array<UserProfile>;
    category: MeetCategory;
    location: Location;
}> {
    return {
        id: value.id,
        organizer: record_opt_to_undefined(await from_candid_opt_n32(_uploadFile, _downloadFile, value.organizer)),
        title: value.title,
        date: value.date,
        createdAt: value.createdAt,
        description: value.description,
        attendees: await from_candid_vec_n23(_uploadFile, _downloadFile, value.attendees),
        category: value.category,
        location: value.location
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_tuple_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [_UserId, _ReactionType]): [UserId, ReactionType] {
    return [
        value[0],
        from_candid_ReactionType_n29(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_tuple_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [_ReactionType, bigint]): [ReactionType, bigint] {
    return [
        from_candid_ReactionType_n29(_uploadFile, _downloadFile, value[0]),
        value[1]
    ];
}
function from_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    buildMaster: null;
} | {
    verified: null;
} | {
    racingLegend: null;
} | {
    dragRacer: null;
} | {
    communityHelper: null;
} | {
    driftKing: null;
} | {
    mechanicPro: null;
}): Badge {
    return "buildMaster" in value ? Badge.buildMaster : "verified" in value ? Badge.verified : "racingLegend" in value ? Badge.racingLegend : "dragRacer" in value ? Badge.dragRacer : "communityHelper" in value ? Badge.communityHelper : "driftKing" in value ? Badge.driftKing : "mechanicPro" in value ? Badge.mechanicPro : value;
}
function from_candid_variant_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    fire: null;
} | {
    hype: null;
} | {
    like: null;
} | {
    wild: null;
} | {
    respect: null;
}): ReactionType {
    return "fire" in value ? ReactionType.fire : "hype" in value ? ReactionType.hype : "like" in value ? ReactionType.like : "wild" in value ? ReactionType.wild : "respect" in value ? ReactionType.respect : value;
}
function from_candid_variant_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: string;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: string;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_vec_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Badge>): Array<Badge> {
    return value.map((x)=>from_candid_Badge_n20(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserProfile>): Promise<Array<UserProfile>> {
    return await Promise.all(value.map(async (x)=>await from_candid_UserProfile_n17(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Video>): Promise<Array<Video>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Video_n25(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[_UserId, _ReactionType]>): Array<[UserId, ReactionType]> {
    return value.map((x)=>from_candid_tuple_n28(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[_ReactionType, bigint]>): Array<[ReactionType, bigint]> {
    return value.map((x)=>from_candid_tuple_n42(_uploadFile, _downloadFile, x));
}
function to_candid_Badge_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Badge): _Badge {
    return to_candid_variant_n15(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_ReactionType_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ReactionType): _ReactionType {
    return to_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ReactionType): {
    fire: null;
} | {
    hype: null;
} | {
    like: null;
} | {
    wild: null;
} | {
    respect: null;
} {
    return value == ReactionType.fire ? {
        fire: null
    } : value == ReactionType.hype ? {
        hype: null
    } : value == ReactionType.like ? {
        like: null
    } : value == ReactionType.wild ? {
        wild: null
    } : value == ReactionType.respect ? {
        respect: null
    } : value;
}
function to_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Badge): {
    buildMaster: null;
} | {
    verified: null;
} | {
    racingLegend: null;
} | {
    dragRacer: null;
} | {
    communityHelper: null;
} | {
    driftKing: null;
} | {
    mechanicPro: null;
} {
    return value == Badge.buildMaster ? {
        buildMaster: null
    } : value == Badge.verified ? {
        verified: null
    } : value == Badge.racingLegend ? {
        racingLegend: null
    } : value == Badge.dragRacer ? {
        dragRacer: null
    } : value == Badge.communityHelper ? {
        communityHelper: null
    } : value == Badge.driftKing ? {
        driftKing: null
    } : value == Badge.mechanicPro ? {
        mechanicPro: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
