/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Category = string;
export interface Comment {
  'id' : CommentId,
  'authorId' : UserId,
  'text' : string,
  'authorName' : string,
  'timestamp' : Time,
  'videoId' : VideoId,
}
export type CommentId = bigint;
export type ExternalBlob = Uint8Array;
export type Hashtag = string;
export type ReactionType = { 'fire' : null } |
  { 'hype' : null } |
  { 'like' : null } |
  { 'wild' : null } |
  { 'respect' : null };
export type Time = bigint;
export type UserId = Principal;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface Video {
  'id' : VideoId,
  'title' : string,
  'thumbnail' : ExternalBlob,
  'hashtags' : Array<Hashtag>,
  'description' : string,
  'mediaUrl' : ExternalBlob,
  'likes' : Array<UserId>,
  'viewCount' : bigint,
  'timestamp' : Time,
  'mediaType' : { 'video' : null } |
    { 'photo' : null },
  'category' : Category,
  'uploader' : UserId,
  'comments' : Array<Comment>,
  'reactions' : Array<[UserId, ReactionType]>,
}
export type VideoId = string;
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'uploadVideo' : ActorMethod<
    [
      string,
      string,
      Array<Hashtag>,
      Category,
      ExternalBlob,
      ExternalBlob,
      { 'video' : null } |
        { 'photo' : null },
    ],
    Video
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];