/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CarMeet {
  'id' : CarMeetId,
  'organizer' : UserId,
  'title' : string,
  'date' : Time,
  'createdAt' : Time,
  'description' : string,
  'attendees' : Array<UserId>,
  'category' : MeetCategory,
  'location' : Location,
}
export interface CarMeetDetails {
  'id' : CarMeetId,
  'organizer' : [] | [UserProfile],
  'title' : string,
  'date' : Time,
  'createdAt' : Time,
  'description' : string,
  'attendees' : Array<UserProfile>,
  'category' : MeetCategory,
  'location' : Location,
}
export type CarMeetId = string;
export type Category = string;
export interface Comment {
  'id' : CommentId,
  'authorId' : UserId,
  'text' : string,
  'timestamp' : Time,
  'videoId' : VideoId,
}
export type CommentId = bigint;
export interface ConversationSummary {
  'lastMessage' : DirectMessage,
  'otherUser' : UserId,
  'unreadCount' : bigint,
}
export interface DirectMessage {
  'id' : MessageId,
  'text' : string,
  'isRead' : boolean,
  'toUser' : UserId,
  'timestamp' : Time,
  'fromUser' : UserId,
}
export type ExternalBlob = Uint8Array;
export type Hashtag = string;
export type Location = string;
export interface MechanicsComment {
  'id' : CommentId,
  'authorId' : UserId,
  'text' : string,
  'timestamp' : Time,
  'postId' : bigint,
}
export interface MechanicsPost {
  'id' : bigint,
  'title' : string,
  'createdAt' : Time,
  'description' : string,
  'author' : UserId,
  'category' : string,
  'comments' : Array<MechanicsComment>,
}
export type MeetCategory = string;
export type MessageId = bigint;
export type Time = bigint;
export type UserId = Principal;
export interface UserProfile {
  'id' : UserId,
  'bio' : string,
  'username' : string,
  'avatarUrl' : string,
  'avatar' : ExternalBlob,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface Video {
  'id' : VideoId,
  'title' : string,
  'thumbnail' : ExternalBlob,
  'hashtags' : Array<Hashtag>,
  'description' : string,
  'likes' : Array<UserId>,
  'timestamp' : Time,
  'category' : Category,
  'uploader' : UserId,
  'comments' : Array<Comment>,
  'videoUrl' : ExternalBlob,
}
export type VideoId = string;
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  /**
   * / Add a comment to a video. Requires #user role.
   */
  'addComment' : ActorMethod<[VideoId, string], undefined>,
  /**
   * / Add a comment to a mechanics post. Requires #user role.
   */
  'addMechanicsComment' : ActorMethod<[bigint, string], MechanicsComment>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  /**
   * / Create a new car meet/event. Requires #user role.
   */
  'createCarMeet' : ActorMethod<
    [string, Location, Time, string, MeetCategory],
    CarMeet
  >,
  /**
   * / Create a new mechanics post. Requires #user role.
   */
  'createMechanicsPost' : ActorMethod<[string, string, string], MechanicsPost>,
  /**
   * / Create a new user account. Open to all callers (guests register here).
   */
  'createUser' : ActorMethod<
    [string, string, ExternalBlob, string],
    UserProfile
  >,
  /**
   * / Delete a mechanics post. Only the author or an admin can delete.
   * / Requires #user role.
   */
  'deleteMechanicsPost' : ActorMethod<[bigint], undefined>,
  /**
   * / Delete a message. Requires #user role.
   * / Only the sender of the message may delete it.
   */
  'deleteMessage' : ActorMethod<[UserId, MessageId], undefined>,
  /**
   * / Delete a user account. Admin-only.
   */
  'deleteUser' : ActorMethod<[UserId], undefined>,
  /**
   * / Delete a video and all associated comments and likes.
   * / Requires #user role. Only the uploader or an admin can delete.
   */
  'deleteVideo' : ActorMethod<[VideoId], undefined>,
  /**
   * / Follow another user. Requires #user role.
   */
  'followUser' : ActorMethod<[UserId], undefined>,
  /**
   * / Get all car meets (sorted by date). Public.
   */
  'getAllCarMeets' : ActorMethod<[], Array<CarMeet>>,
  /**
   * / Get all mechanics posts. Public — no auth check needed.
   */
  'getAllMechanicsPosts' : ActorMethod<[], Array<MechanicsPost>>,
  /**
   * / Get all videos. Public — no auth check needed.
   */
  'getAllVideos' : ActorMethod<[], Array<Video>>,
  /**
   * / Get the caller's own profile. Requires #user role.
   */
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  /**
   * / Get a car meet by ID. Public.
   */
  'getCarMeetById' : ActorMethod<[CarMeetId], [] | [CarMeet]>,
  /**
   * / Get detailed information on a car meet, including attendees' usernames and organizer. Public.
   */
  'getCarMeetDetails' : ActorMethod<[CarMeetId], [] | [CarMeetDetails]>,
  /**
   * / Get car meets by category. Public.
   */
  'getCarMeetsByCategory' : ActorMethod<[MeetCategory], Array<CarMeet>>,
  /**
   * / Get car meets by organizer. Public.
   */
  'getCarMeetsByOrganizer' : ActorMethod<[UserId], Array<CarMeet>>,
  /**
   * / Get comments for a video. Public — no auth check needed.
   */
  'getComments' : ActorMethod<[VideoId], Array<Comment>>,
  /**
   * / Get all messages between the caller and another user, sorted by timestamp ascending.
   * / Requires #user role — only authenticated users can read their own conversations.
   */
  'getConversation' : ActorMethod<[UserId], Array<DirectMessage>>,
  /**
   * / Get the inbox for the caller: most recent message per conversation partner,
   * / sorted by latest timestamp descending.
   * / Requires #user role — only authenticated users can read their own inbox.
   */
  'getInbox' : ActorMethod<[], Array<ConversationSummary>>,
  /**
   * / Get a mechanics post by ID. Public — no auth check needed.
   */
  'getMechanicsPostById' : ActorMethod<[bigint], [] | [MechanicsPost]>,
  /**
   * / Get the caller's own profile. Requires #user role.
   */
  'getOwnProfile' : ActorMethod<[], UserProfile>,
  /**
   * / Get any user's profile by principal. Public — no auth check needed.
   */
  'getProfile' : ActorMethod<[UserId], UserProfile>,
  /**
   * / Get trending videos (top 10 by likes). Public — no auth check needed.
   */
  'getTrendingVideos' : ActorMethod<[], Array<Video>>,
  /**
   * / Get any user's profile by principal. Public — no auth check needed.
   */
  'getUserProfile' : ActorMethod<[UserId], [] | [UserProfile]>,
  /**
   * / Get a single video by ID. Public — no auth check needed.
   */
  'getVideo' : ActorMethod<[VideoId], Video>,
  /**
   * / Get videos filtered by category. Public — no auth check needed.
   */
  'getVideosByCategory' : ActorMethod<[Category], Array<Video>>,
  /**
   * / Get videos filtered by hashtag. Public — no auth check needed.
   */
  'getVideosByHashtag' : ActorMethod<[Hashtag], Array<Video>>,
  /**
   * / Check if the caller is an admin. Public — no auth check needed (returns bool).
   */
  'isAdmin' : ActorMethod<[], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  /**
   * / Join a car meet. Requires #user role.
   */
  'joinCarMeet' : ActorMethod<[CarMeetId], CarMeet>,
  /**
   * / Leave a car meet. Requires #user role.
   */
  'leaveCarMeet' : ActorMethod<[CarMeetId], CarMeet>,
  /**
   * / Mark a specific message as read. Requires #user role.
   * / Only the recipient of the message may mark it as read.
   */
  'markAsRead' : ActorMethod<[UserId, MessageId], undefined>,
  /**
   * / Save (create or update) the caller's profile. Requires #user role.
   */
  'saveCallerUserProfile' : ActorMethod<
    [string, string, ExternalBlob, string],
    undefined
  >,
  /**
   * / Send a direct message to another user. Requires #user role.
   */
  'sendMessage' : ActorMethod<[UserId, string], MessageId>,
  /**
   * / Toggle like on a video. Requires #user role.
   */
  'toggleLike' : ActorMethod<[VideoId], Video>,
  /**
   * / Unfollow another user. Requires #user role.
   */
  'unfollowUser' : ActorMethod<[UserId], undefined>,
  'updateAvatar' : ActorMethod<[string], UserProfile>,
  /**
   * / Update the caller's profile. Requires #user role.
   */
  'updateProfile' : ActorMethod<
    [string, string, ExternalBlob, string],
    UserProfile
  >,
  /**
   * / Upload a new video. Requires #user role.
   */
  'uploadVideo' : ActorMethod<
    [string, string, Array<Hashtag>, Category, ExternalBlob, ExternalBlob],
    Video
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];