/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Badge = { 'buildMaster' : null } |
  { 'verified' : null } |
  { 'racingLegend' : null } |
  { 'dragRacer' : null } |
  { 'communityHelper' : null } |
  { 'driftKing' : null } |
  { 'mechanicPro' : null };
export type Category = string;
export interface Comment {
  'id' : CommentId,
  'authorId' : UserId,
  'text' : string,
  'authorName' : string,
  'timestamp' : Time,
  'videoId' : VideoId,
}
export type CommentId = bigint;
export interface ConversationSummary {
  'lastMessage' : DirectMessage,
  'otherUser' : UserId,
  'unreadCount' : bigint,
}
export interface DirectMessage {
  'id' : MessageId,
  'text' : string,
  'isRead' : boolean,
  'toUser' : UserId,
  'timestamp' : Time,
  'fromUser' : UserId,
}
export type ExternalBlob = Uint8Array;
export type Hashtag = string;
export type MessageId = bigint;
export type ProfileResult = { 'ok' : UserProfile } |
  { 'notFound' : string } |
  { 'unauthorized' : string };
export interface Reaction { 'user' : UserId, 'reactionType' : ReactionType }
export type ReactionType = { 'fire' : null } |
  { 'hype' : null } |
  { 'like' : null } |
  { 'wild' : null } |
  { 'respect' : null };
export type Result = { 'ok' : string } |
  { 'notFound' : string } |
  { 'internalError' : string } |
  { 'unauthorized' : string };
export type Time = bigint;
export type UploadResponse = { 'ok' : { 'blob' : ExternalBlob } } |
  { 'error' : string };
export type UserId = Principal;
export interface UserProfile {
  'id' : UserId,
  'bio' : string,
  'verified' : boolean,
  'username' : string,
  'badges' : Array<Badge>,
  'joinedAt' : bigint,
  'avatarUrl' : string,
  'savedVideos' : Array<bigint>,
  'avatar' : ExternalBlob,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface Video {
  'id' : VideoId,
  'title' : string,
  'thumbnail' : ExternalBlob,
  'hashtags' : Array<Hashtag>,
  'description' : string,
  'mediaUrl' : ExternalBlob,
  'likes' : Array<UserId>,
  'viewCount' : bigint,
  'timestamp' : Time,
  'mediaType' : { 'video' : null } |
    { 'photo' : null },
  'category' : Category,
  'uploader' : UserId,
  'comments' : Array<Comment>,
  'reactions' : Array<Reaction>,
}
export type VideoId = string;
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  /**
   * / Add a comment to a video. Only registered users can comment.
   */
  'addComment' : ActorMethod<[VideoId, string], Result>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  /**
   * / Create a video post. Only registered users can upload content.
   */
  'createVideo' : ActorMethod<
    [
      string,
      string,
      string,
      Array<Hashtag>,
      ExternalBlob,
      ExternalBlob,
      { 'video' : null } |
        { 'photo' : null },
    ],
    Result
  >,
  /**
   * / Delete a conversation with another user.
   * / Only registered users can delete their own conversations.
   * / Only the caller's own conversation copy is deleted (ownership enforced by using caller as key).
   */
  'deleteConversation' : ActorMethod<[Principal], undefined>,
  /**
   * / Delete a reel (video or photo) by its owner or an admin.
   * / Only the owner or an admin can delete a reel.
   */
  'deleteReel' : ActorMethod<[string], Result>,
  /**
   * / Get the caller's own profile. Returns \`#unauthorized\` if the caller is not a registered user,
   * / and \`#notFound\` if the profile does not exist.
   */
  'getCallerUserProfile' : ActorMethod<[], ProfileResult>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  /**
   * / Get comments for a video. Accessible to any caller including guests.
   */
  'getComments' : ActorMethod<[VideoId], Array<Comment>>,
  /**
   * / Get the conversation between the caller and a recipient.
   * / Only registered users can access their conversations.
   * / Only the caller's own conversation is accessible (ownership enforced by using caller as key).
   */
  'getConversation' : ActorMethod<[Principal], Array<DirectMessage>>,
  /**
   * / Get the inbox (conversation summaries) for the caller.
   * / Only registered users can access their inbox.
   */
  'getInbox' : ActorMethod<[], Array<ConversationSummary>>,
  /**
   * / Get the unread message count for a conversation with another user.
   * / Only registered users can query their own unread message counts.
   */
  'getUnreadMessagesCount' : ActorMethod<[Principal], bigint>,
  /**
   * / Get any user's public profile by principal.
   * / Any caller (including guests) can view public profiles, which is required for
   * / social features such as leaderboards, car meets, challenges, and follower lists.
   */
  'getUserProfile' : ActorMethod<[Principal], ProfileResult>,
  /**
   * / Get all reels (videos/photos) for a specific user.
   * / Accessible to any caller including guests (public profile viewing).
   */
  'getUserReels' : ActorMethod<[UserId], Array<Video>>,
  /**
   * / Get all videos. Accessible to any caller including guests (public feed).
   */
  'getVideos' : ActorMethod<[], Array<Video>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  /**
   * / Mark all messages from a sender as read for the caller.
   * / Only registered users can mark messages as read.
   * / Only the caller's own messages can be marked as read (ownership enforced by using caller as key).
   */
  'markMessagesRead' : ActorMethod<[Principal], undefined>,
  /**
   * / Save (create or update) the caller's own profile. Only registered users can save profiles.
   */
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  /**
   * / Send a direct message to a recipient.
   * / Only registered users can send messages.
   */
  'sendMessage' : ActorMethod<[Principal, string], undefined>,
  /**
   * / Like/unlike video with toggle endpoint. Only registered users can like/unlike.
   */
  'toggleLike' : ActorMethod<[VideoId], Result>,
  /**
   * / Upload a blob (photo or video) and return its canister path.
   * / Only registered users are allowed to upload blobs.
   */
  'uploadBlob' : ActorMethod<[ExternalBlob], UploadResponse>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];