/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Hashtag = IDL.Text;
export const Category = IDL.Text;
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const VideoId = IDL.Text;
export const UserId = IDL.Principal;
export const Time = IDL.Int;
export const CommentId = IDL.Nat;
export const Comment = IDL.Record({
  'id' : CommentId,
  'authorId' : UserId,
  'text' : IDL.Text,
  'authorName' : IDL.Text,
  'timestamp' : Time,
  'videoId' : VideoId,
});
export const ReactionType = IDL.Variant({
  'fire' : IDL.Null,
  'hype' : IDL.Null,
  'like' : IDL.Null,
  'wild' : IDL.Null,
  'respect' : IDL.Null,
});
export const Video = IDL.Record({
  'id' : VideoId,
  'title' : IDL.Text,
  'thumbnail' : ExternalBlob,
  'hashtags' : IDL.Vec(Hashtag),
  'description' : IDL.Text,
  'mediaUrl' : ExternalBlob,
  'likes' : IDL.Vec(UserId),
  'viewCount' : IDL.Nat,
  'timestamp' : Time,
  'mediaType' : IDL.Variant({ 'video' : IDL.Null, 'photo' : IDL.Null }),
  'category' : Category,
  'uploader' : UserId,
  'comments' : IDL.Vec(Comment),
  'reactions' : IDL.Vec(IDL.Tuple(UserId, ReactionType)),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'uploadVideo' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Vec(Hashtag),
        Category,
        ExternalBlob,
        ExternalBlob,
        IDL.Variant({ 'video' : IDL.Null, 'photo' : IDL.Null }),
      ],
      [Video],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Hashtag = IDL.Text;
  const Category = IDL.Text;
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const VideoId = IDL.Text;
  const UserId = IDL.Principal;
  const Time = IDL.Int;
  const CommentId = IDL.Nat;
  const Comment = IDL.Record({
    'id' : CommentId,
    'authorId' : UserId,
    'text' : IDL.Text,
    'authorName' : IDL.Text,
    'timestamp' : Time,
    'videoId' : VideoId,
  });
  const ReactionType = IDL.Variant({
    'fire' : IDL.Null,
    'hype' : IDL.Null,
    'like' : IDL.Null,
    'wild' : IDL.Null,
    'respect' : IDL.Null,
  });
  const Video = IDL.Record({
    'id' : VideoId,
    'title' : IDL.Text,
    'thumbnail' : ExternalBlob,
    'hashtags' : IDL.Vec(Hashtag),
    'description' : IDL.Text,
    'mediaUrl' : ExternalBlob,
    'likes' : IDL.Vec(UserId),
    'viewCount' : IDL.Nat,
    'timestamp' : Time,
    'mediaType' : IDL.Variant({ 'video' : IDL.Null, 'photo' : IDL.Null }),
    'category' : Category,
    'uploader' : UserId,
    'comments' : IDL.Vec(Comment),
    'reactions' : IDL.Vec(IDL.Tuple(UserId, ReactionType)),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'uploadVideo' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Vec(Hashtag),
          Category,
          ExternalBlob,
          ExternalBlob,
          IDL.Variant({ 'video' : IDL.Null, 'photo' : IDL.Null }),
        ],
        [Video],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };