/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const VideoId = IDL.Text;
export const CommentId = IDL.Nat;
export const UserId = IDL.Principal;
export const Time = IDL.Int;
export const MechanicsComment = IDL.Record({
  'id' : CommentId,
  'authorId' : UserId,
  'text' : IDL.Text,
  'timestamp' : Time,
  'postId' : IDL.Nat,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Location = IDL.Text;
export const MeetCategory = IDL.Text;
export const CarMeetId = IDL.Text;
export const CarMeet = IDL.Record({
  'id' : CarMeetId,
  'organizer' : UserId,
  'title' : IDL.Text,
  'date' : Time,
  'createdAt' : Time,
  'description' : IDL.Text,
  'attendees' : IDL.Vec(UserId),
  'category' : MeetCategory,
  'location' : Location,
});
export const MechanicsPost = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'createdAt' : Time,
  'description' : IDL.Text,
  'author' : UserId,
  'category' : IDL.Text,
  'comments' : IDL.Vec(MechanicsComment),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const UserProfile = IDL.Record({
  'id' : UserId,
  'bio' : IDL.Text,
  'username' : IDL.Text,
  'avatarUrl' : IDL.Text,
  'avatar' : ExternalBlob,
});
export const MessageId = IDL.Nat;
export const Hashtag = IDL.Text;
export const Category = IDL.Text;
export const Comment = IDL.Record({
  'id' : CommentId,
  'authorId' : UserId,
  'text' : IDL.Text,
  'timestamp' : Time,
  'videoId' : VideoId,
});
export const Video = IDL.Record({
  'id' : VideoId,
  'title' : IDL.Text,
  'thumbnail' : ExternalBlob,
  'hashtags' : IDL.Vec(Hashtag),
  'description' : IDL.Text,
  'likes' : IDL.Vec(UserId),
  'timestamp' : Time,
  'category' : Category,
  'uploader' : UserId,
  'comments' : IDL.Vec(Comment),
  'videoUrl' : ExternalBlob,
});
export const CarMeetDetails = IDL.Record({
  'id' : CarMeetId,
  'organizer' : IDL.Opt(UserProfile),
  'title' : IDL.Text,
  'date' : Time,
  'createdAt' : Time,
  'description' : IDL.Text,
  'attendees' : IDL.Vec(UserProfile),
  'category' : MeetCategory,
  'location' : Location,
});
export const DirectMessage = IDL.Record({
  'id' : MessageId,
  'text' : IDL.Text,
  'isRead' : IDL.Bool,
  'toUser' : UserId,
  'timestamp' : Time,
  'fromUser' : UserId,
});
export const ConversationSummary = IDL.Record({
  'lastMessage' : DirectMessage,
  'otherUser' : UserId,
  'unreadCount' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addComment' : IDL.Func([VideoId, IDL.Text], [], []),
  'addMechanicsComment' : IDL.Func([IDL.Nat, IDL.Text], [MechanicsComment], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createCarMeet' : IDL.Func(
      [IDL.Text, Location, Time, IDL.Text, MeetCategory],
      [CarMeet],
      [],
    ),
  'createMechanicsPost' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [MechanicsPost],
      [],
    ),
  'createUser' : IDL.Func(
      [IDL.Text, IDL.Text, ExternalBlob, IDL.Text],
      [UserProfile],
      [],
    ),
  'deleteMechanicsPost' : IDL.Func([IDL.Nat], [], []),
  'deleteMessage' : IDL.Func([UserId, MessageId], [], []),
  'deleteUser' : IDL.Func([UserId], [], []),
  'deleteVideo' : IDL.Func([VideoId], [], []),
  'followUser' : IDL.Func([UserId], [], []),
  'getAllCarMeets' : IDL.Func([], [IDL.Vec(CarMeet)], ['query']),
  'getAllMechanicsPosts' : IDL.Func([], [IDL.Vec(MechanicsPost)], ['query']),
  'getAllVideos' : IDL.Func([], [IDL.Vec(Video)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCarMeetById' : IDL.Func([CarMeetId], [IDL.Opt(CarMeet)], ['query']),
  'getCarMeetDetails' : IDL.Func(
      [CarMeetId],
      [IDL.Opt(CarMeetDetails)],
      ['query'],
    ),
  'getCarMeetsByCategory' : IDL.Func(
      [MeetCategory],
      [IDL.Vec(CarMeet)],
      ['query'],
    ),
  'getCarMeetsByOrganizer' : IDL.Func([UserId], [IDL.Vec(CarMeet)], ['query']),
  'getComments' : IDL.Func([VideoId], [IDL.Vec(Comment)], ['query']),
  'getConversation' : IDL.Func([UserId], [IDL.Vec(DirectMessage)], ['query']),
  'getInbox' : IDL.Func([], [IDL.Vec(ConversationSummary)], ['query']),
  'getMechanicsPostById' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(MechanicsPost)],
      ['query'],
    ),
  'getOwnProfile' : IDL.Func([], [UserProfile], ['query']),
  'getProfile' : IDL.Func([UserId], [UserProfile], ['query']),
  'getTrendingVideos' : IDL.Func([], [IDL.Vec(Video)], ['query']),
  'getUserProfile' : IDL.Func([UserId], [IDL.Opt(UserProfile)], ['query']),
  'getVideo' : IDL.Func([VideoId], [Video], ['query']),
  'getVideosByCategory' : IDL.Func([Category], [IDL.Vec(Video)], ['query']),
  'getVideosByHashtag' : IDL.Func([Hashtag], [IDL.Vec(Video)], ['query']),
  'isAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'joinCarMeet' : IDL.Func([CarMeetId], [CarMeet], []),
  'leaveCarMeet' : IDL.Func([CarMeetId], [CarMeet], []),
  'markAsRead' : IDL.Func([UserId, MessageId], [], []),
  'saveCallerUserProfile' : IDL.Func(
      [IDL.Text, IDL.Text, ExternalBlob, IDL.Text],
      [],
      [],
    ),
  'sendMessage' : IDL.Func([UserId, IDL.Text], [MessageId], []),
  'toggleLike' : IDL.Func([VideoId], [Video], []),
  'unfollowUser' : IDL.Func([UserId], [], []),
  'updateAvatar' : IDL.Func([IDL.Text], [UserProfile], []),
  'updateProfile' : IDL.Func(
      [IDL.Text, IDL.Text, ExternalBlob, IDL.Text],
      [UserProfile],
      [],
    ),
  'uploadVideo' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Vec(Hashtag),
        Category,
        ExternalBlob,
        ExternalBlob,
      ],
      [Video],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const VideoId = IDL.Text;
  const CommentId = IDL.Nat;
  const UserId = IDL.Principal;
  const Time = IDL.Int;
  const MechanicsComment = IDL.Record({
    'id' : CommentId,
    'authorId' : UserId,
    'text' : IDL.Text,
    'timestamp' : Time,
    'postId' : IDL.Nat,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Location = IDL.Text;
  const MeetCategory = IDL.Text;
  const CarMeetId = IDL.Text;
  const CarMeet = IDL.Record({
    'id' : CarMeetId,
    'organizer' : UserId,
    'title' : IDL.Text,
    'date' : Time,
    'createdAt' : Time,
    'description' : IDL.Text,
    'attendees' : IDL.Vec(UserId),
    'category' : MeetCategory,
    'location' : Location,
  });
  const MechanicsPost = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'createdAt' : Time,
    'description' : IDL.Text,
    'author' : UserId,
    'category' : IDL.Text,
    'comments' : IDL.Vec(MechanicsComment),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const UserProfile = IDL.Record({
    'id' : UserId,
    'bio' : IDL.Text,
    'username' : IDL.Text,
    'avatarUrl' : IDL.Text,
    'avatar' : ExternalBlob,
  });
  const MessageId = IDL.Nat;
  const Hashtag = IDL.Text;
  const Category = IDL.Text;
  const Comment = IDL.Record({
    'id' : CommentId,
    'authorId' : UserId,
    'text' : IDL.Text,
    'timestamp' : Time,
    'videoId' : VideoId,
  });
  const Video = IDL.Record({
    'id' : VideoId,
    'title' : IDL.Text,
    'thumbnail' : ExternalBlob,
    'hashtags' : IDL.Vec(Hashtag),
    'description' : IDL.Text,
    'likes' : IDL.Vec(UserId),
    'timestamp' : Time,
    'category' : Category,
    'uploader' : UserId,
    'comments' : IDL.Vec(Comment),
    'videoUrl' : ExternalBlob,
  });
  const CarMeetDetails = IDL.Record({
    'id' : CarMeetId,
    'organizer' : IDL.Opt(UserProfile),
    'title' : IDL.Text,
    'date' : Time,
    'createdAt' : Time,
    'description' : IDL.Text,
    'attendees' : IDL.Vec(UserProfile),
    'category' : MeetCategory,
    'location' : Location,
  });
  const DirectMessage = IDL.Record({
    'id' : MessageId,
    'text' : IDL.Text,
    'isRead' : IDL.Bool,
    'toUser' : UserId,
    'timestamp' : Time,
    'fromUser' : UserId,
  });
  const ConversationSummary = IDL.Record({
    'lastMessage' : DirectMessage,
    'otherUser' : UserId,
    'unreadCount' : IDL.Nat,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addComment' : IDL.Func([VideoId, IDL.Text], [], []),
    'addMechanicsComment' : IDL.Func(
        [IDL.Nat, IDL.Text],
        [MechanicsComment],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createCarMeet' : IDL.Func(
        [IDL.Text, Location, Time, IDL.Text, MeetCategory],
        [CarMeet],
        [],
      ),
    'createMechanicsPost' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [MechanicsPost],
        [],
      ),
    'createUser' : IDL.Func(
        [IDL.Text, IDL.Text, ExternalBlob, IDL.Text],
        [UserProfile],
        [],
      ),
    'deleteMechanicsPost' : IDL.Func([IDL.Nat], [], []),
    'deleteMessage' : IDL.Func([UserId, MessageId], [], []),
    'deleteUser' : IDL.Func([UserId], [], []),
    'deleteVideo' : IDL.Func([VideoId], [], []),
    'followUser' : IDL.Func([UserId], [], []),
    'getAllCarMeets' : IDL.Func([], [IDL.Vec(CarMeet)], ['query']),
    'getAllMechanicsPosts' : IDL.Func([], [IDL.Vec(MechanicsPost)], ['query']),
    'getAllVideos' : IDL.Func([], [IDL.Vec(Video)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCarMeetById' : IDL.Func([CarMeetId], [IDL.Opt(CarMeet)], ['query']),
    'getCarMeetDetails' : IDL.Func(
        [CarMeetId],
        [IDL.Opt(CarMeetDetails)],
        ['query'],
      ),
    'getCarMeetsByCategory' : IDL.Func(
        [MeetCategory],
        [IDL.Vec(CarMeet)],
        ['query'],
      ),
    'getCarMeetsByOrganizer' : IDL.Func(
        [UserId],
        [IDL.Vec(CarMeet)],
        ['query'],
      ),
    'getComments' : IDL.Func([VideoId], [IDL.Vec(Comment)], ['query']),
    'getConversation' : IDL.Func([UserId], [IDL.Vec(DirectMessage)], ['query']),
    'getInbox' : IDL.Func([], [IDL.Vec(ConversationSummary)], ['query']),
    'getMechanicsPostById' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(MechanicsPost)],
        ['query'],
      ),
    'getOwnProfile' : IDL.Func([], [UserProfile], ['query']),
    'getProfile' : IDL.Func([UserId], [UserProfile], ['query']),
    'getTrendingVideos' : IDL.Func([], [IDL.Vec(Video)], ['query']),
    'getUserProfile' : IDL.Func([UserId], [IDL.Opt(UserProfile)], ['query']),
    'getVideo' : IDL.Func([VideoId], [Video], ['query']),
    'getVideosByCategory' : IDL.Func([Category], [IDL.Vec(Video)], ['query']),
    'getVideosByHashtag' : IDL.Func([Hashtag], [IDL.Vec(Video)], ['query']),
    'isAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'joinCarMeet' : IDL.Func([CarMeetId], [CarMeet], []),
    'leaveCarMeet' : IDL.Func([CarMeetId], [CarMeet], []),
    'markAsRead' : IDL.Func([UserId, MessageId], [], []),
    'saveCallerUserProfile' : IDL.Func(
        [IDL.Text, IDL.Text, ExternalBlob, IDL.Text],
        [],
        [],
      ),
    'sendMessage' : IDL.Func([UserId, IDL.Text], [MessageId], []),
    'toggleLike' : IDL.Func([VideoId], [Video], []),
    'unfollowUser' : IDL.Func([UserId], [], []),
    'updateAvatar' : IDL.Func([IDL.Text], [UserProfile], []),
    'updateProfile' : IDL.Func(
        [IDL.Text, IDL.Text, ExternalBlob, IDL.Text],
        [UserProfile],
        [],
      ),
    'uploadVideo' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Vec(Hashtag),
          Category,
          ExternalBlob,
          ExternalBlob,
        ],
        [Video],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };